services:
    snowflake-proxy:
        network_mode: host
        image: thetorproject/snowflake-proxy:latest
        container_name: snowflake-proxy
        restart: unless-stopped
        command: [ "-ephemeral-ports-range", "30000:40000" ]
        
